development:
  access_key_id: AKIAI6HA6MXTNHLFICEQ
  secret_access_key: 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
  s3_region: us-east-1

production:
  access_key_id: ENV['AWS_ACCESS_KEY_ID']
  secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
  s3_region: ENV['S3_REGION']